// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTodo = "todo"

// Todo mapped from table <todo>
type Todo struct {
	ID        string         `gorm:"column:id;primaryKey" json:"id"`
	Title     string         `gorm:"column:title" json:"title"`
	Content   string         `gorm:"column:content" json:"content"`
	Tag       string         `gorm:"column:tag" json:"tag"`
	Status    int32          `gorm:"column:status;comment:待办事项状态: 0 未办, 1 已完成" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Owner     int32          `gorm:"column:owner" json:"owner"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
